### PR TITLE
DCOS Enterprise Mesos Support

### PR DESCRIPTION
**Pull request by kstedman9**
Added scheduler for supporting DCOS Enterprise Edition of Mesos in strict mode.  Adds support for a service account to be used.  

Fixed the client code to use the proper response struct from /token endpoint.

Added debug for tracing what is happening when things are not working correctly.

Also beware.  I changed the library imports for gatekeeper so that I could build from local source not build from specific repo source.

### CODE REVIEW

**Comment by nemosupremo** [comment]
> I changed the library imports for gatekeeper so that I could build from local source not build from specific repo source.

Are you using go 1.11 modules? This change is really unorthodox (projects such as [gohugoio/hugo](http://github.com/gohugoio/hugo) and [hashicorp/vault](http://github.com/hashicorp/vault) don't do this) and I think it breaks the toolchain on <go1.10 which depends on finding packages via $GOPATH. I think the addition to support DCOS EE is a great addition, but I can't merge this with the import path potentially being broken.

**Comment by kstedman9** [comment]
I will fix the paths that is fine.  I did it because the docker build kept pulling the code from github instead of my local changes.  It made very hard to debug.  I will work on that today and see if I can get it to work.  I have seen others do it like you said but for some reason it was not working with your project.

**Comment by kstedman9** [comment]
Import Paths are fixed and checked in. Sorry about that.

**Comment by nemosupremo** [comment]
Are you using the dockerfile in this repo? There may be something wrong with it then, it shouldn't be trying to pull the code from github. I'll look into it.

**Pull request merged**
