### PR TITLE
Fixes #65 - Do retries on token renewals

### LINKED ISSUE #65: Token renewal should be retried on failure
Currently a single failure will result gatekeeper sealing it self, even if the error is temporary (network issue, momentarily load etc).
I think that the gatekeeper should perform retries of the token renewals, which would allow it to cope with temporary failures.

### PR DESCRIPTION
**Pull request by imriz**

### CODE REVIEW

**Comment by nemosupremo** [comment]
@imriz,

Thanks for working on this. I was working on this as well and also using backoff - I thought about merging your request but I don't think it solved the problem fully as I had hit this issue recently as well.

Your change only applies the backoff to `TokenTtl()`, but not to `RenewToken()`. If `RenewToken()` experiences a transient failure, Gatekeeper will seal itself as well (because it's token will become invalid). Checkout the PR #66 which also fixes this error. If this looks good to you, I'll merge that and cut a new verision.

Thanks again

**Comment by imriz** [comment]
@nemosupremo I intentionally removed the sealing from renewal failure in my PR.
If renewal fails, it will just try again after half of the remaining TTL.
If looking up our token fails, we use backoff, up to 3 minutes.
If we cannot renew the token until the TTL expires, the token search will fail after all retries, and we seal.

It seemed like an elegant solution to me, and it is working perfectly in our production.

**Comment by imriz** [comment]
See https://github.com/nemosupremo/vault-gatekeeper/pull/66/files#diff-605f1d539fd82176ba9ac1c0fb0d73edL587

**Comment by nemosupremo** [comment]
Yep, I saw the comments - I think your PR is good and I wanted to think about the pros/cons of each implementation. I think I will merge #66 for the following reason - I'd rather fail fast in case the token renewal error isn't transient. For example, I'd like to consider the case where the token cannot be renewed because the token doesn't have or lost it's permission to renew itself as an error.

**Pull request closed without merging**
